# Generated by Django 4.0.5 on 2022-06-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('M', '男性'), ('F', '女性')], default='M', max_length=2, verbose_name='性别'),
        ),
    ]
