# Generated by Django 4.0.5 on 2022-06-21 16:26

from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_userinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubname', models.CharField(max_length=255, unique=True, verbose_name='名称')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='public',
        ),
        migrations.AlterField(
            model_name='book',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=index.models.Book.default_price, max_digits=7, verbose_name='零售价'),
        ),
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.pubname'),
        ),
    ]
