# Generated by Django 4.0.5 on 2022-06-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_extenduserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='index.book'),
        ),
    ]
